apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-orchestrator
  namespace: communications
  labels:
    app: notification-orchestrator
    domain: communications
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-notification-orchestrator
