apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-analytics-service
  namespace: analytics-ai
  labels:
    app: search-analytics-service
    domain: analytics-ai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-search-analytics-service
