replicaCount: 1

image:
  repository: 1dev/server
  tag: "11.3.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6610
  targetPort: 6610

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
