apiVersion: v1
kind: Service
metadata:
  name: brand-service
  namespace: catalog
  labels:
    app: brand-service
    domain: catalog
spec:
  selector:
    app: brand-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50072
      targetPort: grpc
      protocol: TCP
