apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatsapp-service
  namespace: communications
  labels:
    app: whatsapp-service
    domain: communications
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-whatsapp-service
