apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "memcached.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "memcached.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: memcached
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          command:
            - memcached
            - -m
            - {{ .Values.maxMemoryMb | quote }}
            - -c
            - {{ .Values.maxConnections | quote }}
            - -v
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: memcache
              containerPort: 11211
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: memcache
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: memcache
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - --memcached.address=localhost:11211
          ports:
            - name: metrics
              containerPort: 9150
              protocol: TCP
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
        {{- end }}
