apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: commerce
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopos-commerce"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: analytics-ai
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopos-analytics-ai"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: analytics-ai
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopos-flink"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopos-velero"
