#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# upload-sbom.sh — Upload Syft-generated CycloneDX SBOMs to Dependency-Track
#
# Usage:
#   export DEPENDENCY_TRACK_URL="http://dependency-track:8080"
#   export DEPENDENCY_TRACK_API_KEY="your-dt-api-key"
#
#   # Upload all SBOMs for a given service/version:
#   ./upload-sbom.sh shopos 1.2.3
#
#   # Or rely on defaults:
#   ./upload-sbom.sh
#
# Expected input:
#   sbom/*.cdx.json  — CycloneDX JSON SBOMs generated by Syft:
#     syft <image> -o cyclonedx-json=sbom/<service>.cdx.json
#
# Environment variables:
#   DEPENDENCY_TRACK_URL     — DT API base URL (default: http://dependency-track:8080)
#   DEPENDENCY_TRACK_API_KEY — DT API key with BOM_UPLOAD permission
#   SBOM_DIR                 — directory containing *.cdx.json files (default: sbom)
#   PARALLEL                 — set to "true" to upload all SBOMs in parallel (default: false)
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DT_URL="${DEPENDENCY_TRACK_URL:-http://dependency-track:8080}"
DT_API_KEY="${DEPENDENCY_TRACK_API_KEY:?DEPENDENCY_TRACK_API_KEY env var is required}"
PROJECT_NAME="${1:-shopos}"
VERSION="${2:-latest}"
SBOM_DIR="${SBOM_DIR:-sbom}"
PARALLEL="${PARALLEL:-false}"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }
err()  { log "ERROR: $*" >&2; }
warn() { log "WARN:  $*"; }

# Upload a single SBOM file to Dependency-Track
upload_sbom() {
  local sbom_file="$1"
  local project_name="$2"
  local version="$3"

  if [ ! -f "$sbom_file" ]; then
    warn "SBOM file not found: $sbom_file — skipping"
    return 0
  fi

  local svc
  svc=$(basename "$sbom_file" .cdx.json)
  local full_project="${project_name}-${svc}"
  local bom_b64

  log "Uploading SBOM: $sbom_file → project=${full_project} version=${version}"

  # Base64-encode the SBOM (GNU base64: -w0 for no line wrapping)
  if base64 --version 2>&1 | grep -q GNU; then
    bom_b64=$(base64 -w0 "$sbom_file")
  else
    # macOS/BSD base64
    bom_b64=$(base64 "$sbom_file" | tr -d '\n')
  fi

  local http_code
  http_code=$(curl \
    --silent \
    --output /dev/null \
    --write-out "%{http_code}" \
    --request PUT \
    --header "X-Api-Key: ${DT_API_KEY}" \
    --header "Content-Type: application/json" \
    "${DT_URL}/api/v1/bom" \
    --data "{
      \"projectName\": \"${full_project}\",
      \"projectVersion\": \"${version}\",
      \"autoCreate\": true,
      \"bom\": \"${bom_b64}\"
    }")

  if [ "$http_code" -eq 200 ]; then
    log "  OK  (HTTP 200) — ${full_project}:${version}"
  elif [ "$http_code" -eq 401 ]; then
    err "Authentication failed (HTTP 401) — check DEPENDENCY_TRACK_API_KEY"
    return 1
  elif [ "$http_code" -eq 403 ]; then
    err "Forbidden (HTTP 403) — API key lacks BOM_UPLOAD permission"
    return 1
  else
    err "Unexpected HTTP ${http_code} for ${full_project}:${version}"
    return 1
  fi
}

# ── Pre-flight checks ─────────────────────────────────────────────────────────
log "Dependency-Track SBOM uploader"
log "  DT URL:       ${DT_URL}"
log "  Project name: ${PROJECT_NAME}"
log "  Version:      ${VERSION}"
log "  SBOM dir:     ${SBOM_DIR}"

# Verify DT is reachable
if ! curl --silent --fail --max-time 10 "${DT_URL}/api/version" > /dev/null 2>&1; then
  err "Cannot reach Dependency-Track at ${DT_URL}"
  err "Ensure DEPENDENCY_TRACK_URL is correct and the service is running."
  exit 1
fi

DT_VERSION=$(curl --silent --fail --max-time 10 \
  --header "X-Api-Key: ${DT_API_KEY}" \
  "${DT_URL}/api/version" | python3 -c "import sys,json; print(json.load(sys.stdin).get('version','unknown'))" 2>/dev/null || echo "unknown")
log "  DT version:   ${DT_VERSION}"

# Check SBOM directory
if [ ! -d "${SBOM_DIR}" ]; then
  err "SBOM directory '${SBOM_DIR}' does not exist."
  err "Generate SBOMs with: syft <image> -o cyclonedx-json=${SBOM_DIR}/<service>.cdx.json"
  exit 1
fi

SBOM_COUNT=$(find "${SBOM_DIR}" -name "*.cdx.json" -type f | wc -l | tr -d ' ')
if [ "$SBOM_COUNT" -eq 0 ]; then
  warn "No *.cdx.json files found in ${SBOM_DIR} — nothing to upload."
  exit 0
fi

log "Found ${SBOM_COUNT} SBOM(s) to upload."

# ── Upload all SBOMs ──────────────────────────────────────────────────────────
FAIL_COUNT=0

if [ "$PARALLEL" = "true" ]; then
  log "Uploading in parallel..."
  pids=()
  for sbom in "${SBOM_DIR}"/*.cdx.json; do
    upload_sbom "$sbom" "$PROJECT_NAME" "$VERSION" &
    pids+=($!)
  done
  for pid in "${pids[@]}"; do
    wait "$pid" || FAIL_COUNT=$((FAIL_COUNT + 1))
  done
else
  for sbom in "${SBOM_DIR}"/*.cdx.json; do
    upload_sbom "$sbom" "$PROJECT_NAME" "$VERSION" || FAIL_COUNT=$((FAIL_COUNT + 1))
  done
fi

# ── Summary ───────────────────────────────────────────────────────────────────
log ""
log "Upload complete."
log "  Total:   ${SBOM_COUNT}"
log "  Failed:  ${FAIL_COUNT}"
log "  Success: $((SBOM_COUNT - FAIL_COUNT))"
log ""
log "View projects at: ${DT_URL}/#/projects"

if [ "$FAIL_COUNT" -gt 0 ]; then
  err "${FAIL_COUNT} upload(s) failed. Check the logs above."
  exit 1
fi
