def call(String serviceName) {
    def map = [
        // platform
        'api-gateway'                  : 'go',
        'web-bff'                      : 'go',
        'mobile-bff'                   : 'nodejs',
        'partner-bff'                  : 'go',
        'config-service'               : 'go',
        'feature-flag-service'         : 'go',
        'rate-limiter-service'         : 'go',
        'health-check-service'         : 'go',
        'saga-orchestrator'            : 'go',
        'event-store-service'          : 'go',
        'cache-warming-service'        : 'go',
        'webhook-service'              : 'go',
        'scheduler-service'            : 'go',
        'worker-job-queue'             : 'go',
        'audit-service'                : 'java',
        'load-generator'               : 'python',
        'admin-portal'                 : 'java',
        'graphql-gateway'              : 'go',
        'dead-letter-service'          : 'go',
        'geolocation-service'          : 'go',
        'event-replay-service'         : 'go',
        'tenant-service'               : 'go',
        // identity
        'auth-service'                 : 'rust',
        'user-service'                 : 'java',
        'session-service'              : 'go',
        'permission-service'           : 'go',
        'mfa-service'                  : 'go',
        'gdpr-service'                 : 'go',
        'api-key-service'              : 'go',
        'device-fingerprint-service'   : 'go',
        // catalog
        'product-catalog-service'      : 'go',
        'category-service'             : 'go',
        'brand-service'                : 'go',
        'pricing-service'              : 'java',
        'inventory-service'            : 'go',
        'bundle-service'               : 'go',
        'configurator-service'         : 'nodejs',
        'subscription-product-service' : 'kotlin',
        'search-service'               : 'python',
        'seo-service'                  : 'nodejs',
        'product-import-service'       : 'go',
        'price-list-service'           : 'java',
        // commerce
        'cart-service'                 : 'csharp',
        'checkout-service'             : 'go',
        'order-service'                : 'kotlin',
        'payment-service'              : 'java',
        'shipping-service'             : 'rust',
        'currency-service'             : 'nodejs',
        'tax-service'                  : 'go',
        'promotions-service'           : 'java',
        'loyalty-service'              : 'go',
        'return-refund-service'        : 'csharp',
        'subscription-billing-service' : 'go',
        'fraud-detection-service'      : 'python',
        'wallet-service'               : 'go',
        'ab-testing-service'           : 'go',
        'gift-card-service'            : 'go',
        'address-validation-service'   : 'go',
        'digital-goods-service'        : 'go',
        'voucher-service'              : 'go',
        'pre-order-service'            : 'go',
        'backorder-service'            : 'go',
        'waitlist-service'             : 'go',
        'flash-sale-service'           : 'go',
        'bnpl-service'                 : 'go',
        // supply-chain
        'vendor-service'               : 'java',
        'purchase-order-service'       : 'kotlin',
        'warehouse-service'            : 'go',
        'fulfillment-service'          : 'go',
        'tracking-service'             : 'nodejs',
        'label-service'                : 'python',
        'carrier-integration-service'  : 'go',
        'demand-forecast-service'      : 'python',
        'customs-duties-service'       : 'go',
        'returns-logistics-service'    : 'go',
        'supplier-portal-service'      : 'java',
        'cold-chain-service'           : 'go',
        'supplier-rating-service'      : 'go',
        // financial
        'invoice-service'              : 'java',
        'accounting-service'           : 'kotlin',
        'payout-service'               : 'java',
        'reconciliation-service'       : 'kotlin',
        'tax-reporting-service'        : 'go',
        'expense-management-service'   : 'go',
        'credit-service'               : 'go',
        'kyc-aml-service'              : 'java',
        'budget-service'               : 'go',
        'chargeback-service'           : 'java',
        'revenue-recognition-service'  : 'kotlin',
        // customer-experience
        'review-rating-service'        : 'nodejs',
        'qa-service'                   : 'nodejs',
        'wishlist-service'             : 'go',
        'compare-service'              : 'go',
        'recently-viewed-service'      : 'go',
        'support-ticket-service'       : 'java',
        'live-chat-service'            : 'go',
        'consent-management-service'   : 'nodejs',
        'age-verification-service'     : 'go',
        'survey-service'               : 'nodejs',
        'feedback-service'             : 'nodejs',
        'price-alert-service'          : 'go',
        'back-in-stock-service'        : 'go',
        'gift-registry-service'        : 'go',
        // communications
        'notification-orchestrator'    : 'nodejs',
        'email-service'                : 'python',
        'sms-service'                  : 'nodejs',
        'push-notification-service'    : 'go',
        'template-service'             : 'nodejs',
        'in-app-notification-service'  : 'go',
        'digest-service'               : 'go',
        'whatsapp-service'             : 'nodejs',
        'chatbot-service'              : 'python',
        // content
        'media-asset-service'          : 'go',
        'image-processing-service'     : 'python',
        'document-service'             : 'java',
        'cms-service'                  : 'nodejs',
        'video-service'                : 'go',
        'sitemap-service'              : 'go',
        'i18n-l10n-service'            : 'go',
        'data-export-service'          : 'python',
        // analytics-ai
        'analytics-service'            : 'python',
        'reporting-service'            : 'scala',
        'recommendation-service'       : 'python',
        'sentiment-analysis-service'   : 'python',
        'price-optimization-service'   : 'python',
        'ml-feature-store'             : 'python',
        'personalization-service'      : 'python',
        'data-pipeline-service'        : 'python',
        'ad-service'                   : 'java',
        'event-tracking-service'       : 'python',
        'attribution-service'          : 'python',
        'clv-service'                  : 'python',
        'search-analytics-service'     : 'python',
        // b2b
        'organization-service'         : 'java',
        'contract-service'             : 'kotlin',
        'quote-rfq-service'            : 'go',
        'approval-workflow-service'    : 'go',
        'b2b-credit-limit-service'     : 'go',
        'edi-service'                  : 'java',
        'marketplace-seller-service'   : 'java',
        // integrations
        'erp-integration-service'      : 'java',
        'marketplace-connector-service': 'go',
        'social-commerce-service'      : 'nodejs',
        'crm-integration-service'      : 'go',
        'payment-gateway-integration'  : 'go',
        'logistics-provider-integration': 'go',
        'tax-provider-integration'     : 'go',
        'pim-integration-service'      : 'go',
        'cdp-integration-service'      : 'go',
        'accounting-integration-service': 'java',
        // affiliate
        'affiliate-service'            : 'go',
        'referral-service'             : 'go',
        'influencer-service'           : 'go',
        'commission-payout-service'    : 'go',
    ]
    return map.get(serviceName, 'go')
}
return this
