apiVersion: v1
kind: ServiceAccount
metadata:
  name: ab-testing-service
  namespace: commerce
  labels:
    app: ab-testing-service
    domain: commerce
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-ab-testing-service
