apiVersion: v1
kind: Service
metadata:
  name: purchase-order-service
  namespace: supply-chain
  labels:
    app: purchase-order-service
    domain: supply-chain
spec:
  selector:
    app: purchase-order-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50101
      targetPort: grpc
      protocol: TCP
