apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduktor-gateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conduktor-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.gateway.adminUsername | quote }}
  admin-password: {{ .Values.gateway.adminPassword | quote }}
