apiVersion: v1
kind: Service
metadata:
  name: attribution-service
  namespace: analytics-ai
  labels:
    app: attribution-service
    domain: analytics-ai
spec:
  selector:
    app: attribution-service
  type: ClusterIP
  ports:
    - name: http
      port: 8194
      targetPort: http
      protocol: TCP
