apiVersion: v1
kind: Service
metadata:
  name: support-ticket-service
  namespace: customer-experience
  labels:
    app: support-ticket-service
    domain: customer-experience
spec:
  selector:
    app: support-ticket-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50125
      targetPort: grpc
      protocol: TCP
