replicaCount: 1

image:
  repository: anchore/anchore-engine
  tag: "v1.9.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8228
  targetPort: 8228

persistence:
  enabled: true
  storageClass: ""
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
