spring:
  application:
    name: erp-integration-service

server:
  port: 50170

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
