apiVersion: v1
kind: ServiceAccount
metadata:
  name: sms-service
  namespace: communications
  labels:
    app: sms-service
    domain: communications
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-sms-service
