# External Secrets Operator — pulls Vault/AWS-SM/Azure-KV secrets into K8s Secrets.
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata: { name: external-secrets, namespace: external-secrets }
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 0.10.4
  targetNamespace: external-secrets
  valuesContent: |-
    installCRDs: true
    replicaCount: 2
    serviceMonitor: { enabled: true }
    webhook: { replicaCount: 2 }
    certController: { replicaCount: 2 }
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: { name: vault-shopos }
spec:
  provider:
    vault:
      server: https://vault.infra.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef: { name: external-secrets, namespace: external-secrets }
