apiVersion: v1
kind: ServiceAccount
metadata:
  name: social-commerce-service
  namespace: integrations
  labels:
    app: social-commerce-service
    domain: integrations
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-social-commerce-service
