apiVersion: v1
kind: Service
metadata:
  name: social-commerce-service
  namespace: integrations
  labels:
    app: social-commerce-service
    domain: integrations
spec:
  selector:
    app: social-commerce-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50171
      targetPort: grpc
      protocol: TCP
