apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shopos
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-org/shopos.git
  ref:
    branch: main
