apiVersion: v1
kind: Service
metadata:
  name: {{ include "damage-deposit-service.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "damage-deposit-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: grpc
  selector:
    {{- include "damage-deposit-service.selectorLabels" . | nindent 4 }}
