apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: platform
  labels:
    app: config-service
    domain: platform
spec:
  selector:
    app: config-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
