apiVersion: v1
kind: ServiceAccount
metadata:
  name: mfa-service
  namespace: identity
  labels:
    app: mfa-service
    domain: identity
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-mfa-service
