{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wiremock.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}
