apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: catalog
  labels:
    app: category-service
    domain: catalog
spec:
  selector:
    app: category-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50071
      targetPort: grpc
      protocol: TCP
