apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-bff
  namespace: platform
  labels:
    app: mobile-bff
    domain: platform
data:
  APP_ENV: production
  LOG_LEVEL: info
  LOG_FORMAT: json
  SERVICE_NAME: mobile-bff
  SERVICE_DOMAIN: platform
  HTTP_PORT: "8082"
  METRICS_PORT: "9090"
  HEALTH_PORT: "8082"
  OTEL_SERVICE_NAME: mobile-bff
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring:4317
  KAFKA_BROKERS: kafka.infra:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.infra:8081
