apiVersion: v1
kind: Service
metadata:
  name: template-service
  namespace: communications
  labels:
    app: template-service
    domain: communications
spec:
  selector:
    app: template-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50131
      targetPort: grpc
      protocol: TCP
