replicaCount: 1

image:
  repository: confluentinc/cp-schema-registry
  tag: "7.8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

persistence:
  enabled: false
  storageClass: "standard-rwo"
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /var/lib/data

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
