apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shopos-b2b
  namespace: argocd
spec:
  description: ShopOS b2b domain services
  sourceRepos:
    - 'https://github.com/prabhat-roy/ShopOS.git'
  destinations:
    - namespace: shopos-b2b
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
  roles:
    - name: b2b-admin
      description: b2b team full access
      policies:
        - p, proj:shopos-b2b:b2b-admin, applications, *, shopos-b2b/*, allow
      groups:
        - b2b-team
