apiVersion: v1
kind: Service
metadata:
  name: gift-card-service
  namespace: commerce
  labels:
    app: gift-card-service
    domain: commerce
spec:
  selector:
    app: gift-card-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50094
      targetPort: grpc
      protocol: TCP
