apiVersion: v1
kind: Secret
metadata:
  name: {{ include "surrealdb.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "surrealdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "root"
  password: "changeme-replace-in-production"
