replicaCount: 1

image:
  repository: ghcr.io/fluxcd/flux-cli
  tag: "v2.3.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9292
  targetPort: 9292

persistence:
  enabled: true
  storageClass: ""
  size: 2Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
