apiVersion: v1
kind: Service
metadata:
  name: {{ include "yugabytedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yugabytedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "yugabytedb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yugabytedb.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yugabytedb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5433
      name: ysql
    - port: 9042
      name: ycql
  selector:
    {{- include "yugabytedb.selectorLabels" . | nindent 4 }}
