apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: analytics-ai
  labels:
    app: analytics-service
    domain: analytics-ai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-analytics-service
