apiVersion: v1
kind: Secret
metadata:
  name: {{ include "defectdojo.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "defectdojo.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.app.databaseUrl | quote }}
  secret-key: {{ .Values.app.secretKey | quote }}
