apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketplace-connector-service
  namespace: integrations
  labels:
    app: marketplace-connector-service
    domain: integrations
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-marketplace-connector-service
