apiVersion: v1
kind: ServiceAccount
metadata:
  name: document-service
  namespace: content
  labels:
    app: document-service
    domain: content
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-document-service
