replicaCount: 1

image:
  repository: ghcr.io/loft-sh/vcluster
  tag: "0.20.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
