apiVersion: v1
kind: Service
metadata:
  name: {{- include "stock-reservation-service.fullname" . }}
  namespace: {{- .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "stock-reservation-service.labels" . | nindent 4 }}
spec:
  type: {{- .Values.service.type }}
  selector:
    {{- include "stock-reservation-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{- .Values.service.port }}
      targetPort: {{- .Values.service.targetPort }}
      protocol: {{- .Values.service.protocol }}
