apiVersion: v1
kind: ServiceAccount
metadata:
  name: compare-service
  namespace: customer-experience
  labels:
    app: compare-service
    domain: customer-experience
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-compare-service
