replicaCount: 1

image:
  repository: nats
  tag: "2.12.7-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4222
  targetPort: 4222

persistence:
  enabled: true
  storageClass: """"
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /var/lib/data

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 1Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
