apiVersion: v1
kind: Service
metadata:
  name: {{ include "victoria-logs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victoria-logs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "victoria-logs.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "victoria-logs.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victoria-logs.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "victoria-logs.selectorLabels" . | nindent 4 }}
