replicaCount: 1

image:
  repository: ghcr.io/kellnr/kellnr
  tag: "6.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

persistence:
  enabled: true
  storageClass: """"
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /opt/kellnr/data

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
