replicaCount: 1

image:
  repository: victoriametrics/victoria-metrics
  tag: "v1.103.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8428
  targetPort: 8428

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 50Gi
  accessMode: ReadWriteOnce
  mountPath: /victoria-metrics-data

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
