apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-order-service
  namespace: commerce
  labels:
    app: pre-order-service
    domain: commerce
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-pre-order-service
