apiVersion: v1
kind: ServiceAccount
metadata:
  name: carrier-integration-service
  namespace: supply-chain
  labels:
    app: carrier-integration-service
    domain: supply-chain
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-carrier-integration-service
