#!/usr/bin/env python3
"""Update 'when' conditions in Jenkinsfiles to add booleanParam tool flags."""

files_mappings = {
    'ci/jenkins/networking.Jenkinsfile': {
        "stage('Cilium')": 'CILIUM',
        "stage('Calico')": 'CALICO',
        "stage('Flannel')": 'FLANNEL',
        "stage('Weave Net')": 'WEAVE_NET',
        "stage('Antrea')": 'ANTREA',
        "stage('Nginx Ingress')": 'NGINX_INGRESS',
        "stage('Traefik')": 'TRAEFIK',
        "stage('HAProxy Ingress')": 'HAPROXY_INGRESS',
        "stage('Contour')": 'CONTOUR',
        "stage('Kong')": 'KONG',
        "stage('Istio')": 'ISTIO',
        "stage('Linkerd')": 'LINKERD',
        "stage('Consul')": 'CONSUL',
        "stage('External DNS')": 'EXTERNAL_DNS',
        "stage('Uninstall External DNS')": 'EXTERNAL_DNS',
        "stage('Uninstall Consul')": 'CONSUL',
        "stage('Uninstall Linkerd')": 'LINKERD',
        "stage('Uninstall Istio')": 'ISTIO',
        "stage('Uninstall Kong')": 'KONG',
        "stage('Uninstall Contour')": 'CONTOUR',
        "stage('Uninstall HAProxy Ingress')": 'HAPROXY_INGRESS',
        "stage('Uninstall Traefik')": 'TRAEFIK',
        "stage('Uninstall Nginx Ingress')": 'NGINX_INGRESS',
        "stage('Uninstall Antrea')": 'ANTREA',
        "stage('Uninstall Weave Net')": 'WEAVE_NET',
        "stage('Uninstall Flannel')": 'FLANNEL',
        "stage('Uninstall Calico')": 'CALICO',
        "stage('Uninstall Cilium')": 'CILIUM',
    },
    'ci/jenkins/observability.Jenkinsfile': {
        "stage('Prometheus')": 'PROMETHEUS',
        "stage('Alertmanager')": 'ALERTMANAGER',
        "stage('Thanos')": 'THANOS',
        "stage('Victoria Metrics')": 'VICTORIA_METRICS',
        "stage('Pushgateway')": 'PUSHGATEWAY',
        "stage('Blackbox Exporter')": 'BLACKBOX_EXPORTER',
        "stage('Kube State Metrics')": 'KUBE_STATE_METRICS',
        "stage('Node Exporter')": 'NODE_EXPORTER',
        "stage('Elasticsearch')": 'ELASTICSEARCH',
        "stage('OpenSearch')": 'OPENSEARCH',
        "stage('Loki')": 'LOKI',
        "stage('Fluentd')": 'FLUENTD',
        "stage('Fluent Bit')": 'FLUENT_BIT',
        "stage('Logstash')": 'LOGSTASH',
        "stage('Jaeger')": 'JAEGER',
        "stage('Tempo')": 'TEMPO',
        "stage('Zipkin')": 'ZIPKIN',
        "stage('Grafana')": 'GRAFANA',
        "stage('Kibana')": 'KIBANA',
        "stage('OpenSearch Dashboards')": 'OPENSEARCH_DASHBOARDS',
        "stage('OTel Collector')": 'OTEL_COLLECTOR',
        "stage('Sentry')": 'SENTRY',
        "stage('GlitchTip')": 'GLITCHTIP',
        "stage('Pyrra')": 'PYRRA',
        "stage('Sloth')": 'SLOTH',
        "stage('Uptime Kuma')": 'UPTIME_KUMA',
        "stage('Pyroscope')": 'PYROSCOPE',
        "stage('Robusta')": 'ROBUSTA',
        "stage('OpenCost')": 'OPENCOST',
        "stage('Goldilocks')": 'GOLDILOCKS',
        "stage('Uninstall Goldilocks')": 'GOLDILOCKS',
        "stage('Uninstall OpenCost')": 'OPENCOST',
        "stage('Uninstall Robusta')": 'ROBUSTA',
        "stage('Uninstall Pyroscope')": 'PYROSCOPE',
        "stage('Uninstall Uptime Kuma')": 'UPTIME_KUMA',
        "stage('Uninstall Sloth')": 'SLOTH',
        "stage('Uninstall Pyrra')": 'PYRRA',
        "stage('Uninstall GlitchTip')": 'GLITCHTIP',
        "stage('Uninstall Sentry')": 'SENTRY',
        "stage('Uninstall OTel Collector')": 'OTEL_COLLECTOR',
        "stage('Uninstall OpenSearch Dashboards')": 'OPENSEARCH_DASHBOARDS',
        "stage('Uninstall Kibana')": 'KIBANA',
        "stage('Uninstall Grafana')": 'GRAFANA',
        "stage('Uninstall Zipkin')": 'ZIPKIN',
        "stage('Uninstall Tempo')": 'TEMPO',
        "stage('Uninstall Jaeger')": 'JAEGER',
        "stage('Uninstall Logstash')": 'LOGSTASH',
        "stage('Uninstall Fluent Bit')": 'FLUENT_BIT',
        "stage('Uninstall Fluentd')": 'FLUENTD',
        "stage('Uninstall Loki')": 'LOKI',
        "stage('Uninstall OpenSearch')": 'OPENSEARCH',
        "stage('Uninstall Elasticsearch')": 'ELASTICSEARCH',
        "stage('Uninstall Node Exporter')": 'NODE_EXPORTER',
        "stage('Uninstall Kube State Metrics')": 'KUBE_STATE_METRICS',
        "stage('Uninstall Blackbox Exporter')": 'BLACKBOX_EXPORTER',
        "stage('Uninstall Pushgateway')": 'PUSHGATEWAY',
        "stage('Uninstall Victoria Metrics')": 'VICTORIA_METRICS',
        "stage('Uninstall Thanos')": 'THANOS',
        "stage('Uninstall Alertmanager')": 'ALERTMANAGER',
        "stage('Uninstall Prometheus')": 'PROMETHEUS',
    },
    'ci/jenkins/security.Jenkinsfile': {
        "stage('Keycloak')": 'KEYCLOAK',
        "stage('Dex')": 'DEX',
        "stage('Authentik')": 'AUTHENTIK',
        "stage('ZITADEL')": 'ZITADEL',
        "stage('Authelia')": 'AUTHELIA',
        "stage('SPIRE')": 'SPIRE',
        "stage('Pomerium')": 'POMERIUM',
        "stage('Vault')": 'VAULT',
        "stage('Infisical')": 'INFISICAL',
        "stage('OPA Gatekeeper')": 'OPA_GATEKEEPER',
        "stage('Kyverno')": 'KYVERNO',
        "stage('Kubewarden')": 'KUBEWARDEN',
        "stage('OpenFGA')": 'OPENFGA',
        "stage('Falco')": 'FALCO',
        "stage('Tetragon')": 'TETRAGON',
        "stage('Tracee')": 'TRACEE',
        "stage('KubeArmor')": 'KUBEARMOR',
        "stage('Coraza WAF')": 'CORAZA_WAF',
        "stage('cert-manager')": 'CERT_MANAGER',
        "stage('SonarQube')": 'SONARQUBE',
        "stage('Trivy Operator')": 'TRIVY_OPERATOR',
        "stage('Clair')": 'CLAIR',
        "stage('OpenVAS')": 'OPENVAS',
        "stage('Anchore')": 'ANCHORE',
        "stage('OWASP ZAP')": 'OWASP_ZAP',
        "stage('Nuclei')": 'NUCLEI',
        "stage('Kubescape')": 'KUBESCAPE',
        "stage('Polaris')": 'POLARIS',
        "stage('Rekor')": 'REKOR',
        "stage('Fulcio')": 'FULCIO',
        "stage('Notary')": 'NOTARY',
        "stage('Suricata')": 'SURICATA',
        "stage('Zeek')": 'ZEEK',
        "stage('Wazuh')": 'WAZUH',
        "stage('Dependency Track')": 'DEPENDENCY_TRACK',
        "stage('DefectDojo')": 'DEFECTDOJO',
        "stage('Uninstall DefectDojo')": 'DEFECTDOJO',
        "stage('Uninstall Dependency Track')": 'DEPENDENCY_TRACK',
        "stage('Uninstall Wazuh')": 'WAZUH',
        "stage('Uninstall Zeek')": 'ZEEK',
        "stage('Uninstall Suricata')": 'SURICATA',
        "stage('Uninstall Notary')": 'NOTARY',
        "stage('Uninstall Fulcio')": 'FULCIO',
        "stage('Uninstall Rekor')": 'REKOR',
        "stage('Uninstall Polaris')": 'POLARIS',
        "stage('Uninstall Kubescape')": 'KUBESCAPE',
        "stage('Uninstall Nuclei')": 'NUCLEI',
        "stage('Uninstall OWASP ZAP')": 'OWASP_ZAP',
        "stage('Uninstall Anchore')": 'ANCHORE',
        "stage('Uninstall OpenVAS')": 'OPENVAS',
        "stage('Uninstall Clair')": 'CLAIR',
        "stage('Uninstall Trivy Operator')": 'TRIVY_OPERATOR',
        "stage('Uninstall SonarQube')": 'SONARQUBE',
        "stage('Uninstall cert-manager')": 'CERT_MANAGER',
        "stage('Uninstall Coraza WAF')": 'CORAZA_WAF',
        "stage('Uninstall KubeArmor')": 'KUBEARMOR',
        "stage('Uninstall Tracee')": 'TRACEE',
        "stage('Uninstall Tetragon')": 'TETRAGON',
        "stage('Uninstall Falco')": 'FALCO',
        "stage('Uninstall OpenFGA')": 'OPENFGA',
        "stage('Uninstall Kubewarden')": 'KUBEWARDEN',
        "stage('Uninstall Kyverno')": 'KYVERNO',
        "stage('Uninstall OPA Gatekeeper')": 'OPA_GATEKEEPER',
        "stage('Uninstall Infisical')": 'INFISICAL',
        "stage('Uninstall Vault')": 'VAULT',
        "stage('Uninstall Pomerium')": 'POMERIUM',
        "stage('Uninstall SPIRE')": 'SPIRE',
        "stage('Uninstall Authelia')": 'AUTHELIA',
        "stage('Uninstall ZITADEL')": 'ZITADEL',
        "stage('Uninstall Authentik')": 'AUTHENTIK',
        "stage('Uninstall Dex')": 'DEX',
        "stage('Uninstall Keycloak')": 'KEYCLOAK',
    },
    'ci/jenkins/streaming.Jenkinsfile': {
        "stage('Flink Operator')": 'FLINK',
        "stage('Flink Jobs')": 'FLINK',
        "stage('Debezium \u2014 Postgres CDC')": 'DEBEZIUM_POSTGRES',
        "stage('Debezium \u2014 MongoDB CDC')": 'DEBEZIUM_MONGODB',
        "stage('Uninstall Flink Jobs')": 'FLINK',
        "stage('Uninstall Debezium Connectors')": 'DEBEZIUM_POSTGRES',
        "stage('Uninstall Flink Operator')": 'FLINK',
    },
    'ci/jenkins/gitops.Jenkinsfile': {
        "stage('ArgoCD')": 'ARGOCD',
        "stage('Argo Rollouts')": 'ARGO_ROLLOUTS',
        "stage('Argo Workflows')": 'ARGO_WORKFLOWS',
        "stage('Argo Events')": 'ARGO_EVENTS',
        "stage('ArgoCD Image Updater')": 'ARGOCD_IMAGE_UPDATER',
        "stage('Flux CD')": 'FLUX',
        "stage('Flagger')": 'FLAGGER',
        "stage('Weave GitOps')": 'WEAVE_GITOPS',
        "stage('Sealed Secrets')": 'SEALED_SECRETS',
        "stage('External Secrets')": 'EXTERNAL_SECRETS',
        "stage('vCluster')": 'VCLUSTER',
        "stage('Gimlet')": 'GIMLET',
        "stage('Uninstall Gimlet')": 'GIMLET',
        "stage('Uninstall vCluster')": 'VCLUSTER',
        "stage('Uninstall External Secrets')": 'EXTERNAL_SECRETS',
        "stage('Uninstall Sealed Secrets')": 'SEALED_SECRETS',
        "stage('Uninstall Weave GitOps')": 'WEAVE_GITOPS',
        "stage('Uninstall Flagger')": 'FLAGGER',
        "stage('Uninstall Flux CD')": 'FLUX',
        "stage('Uninstall ArgoCD Image Updater')": 'ARGOCD_IMAGE_UPDATER',
        "stage('Uninstall Argo Events')": 'ARGO_EVENTS',
        "stage('Uninstall Argo Workflows')": 'ARGO_WORKFLOWS',
        "stage('Uninstall Argo Rollouts')": 'ARGO_ROLLOUTS',
        "stage('Uninstall ArgoCD')": 'ARGOCD',
    },
}

action_install = "when { expression { params.ACTION == 'INSTALL' } }"
action_uninstall = "when { expression { params.ACTION == 'UNINSTALL' } }"

for filepath, mappings in files_mappings.items():
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    lines = content.split('\n')
    current_stage = None
    result = []
    for line in lines:
        for stage_name, param in mappings.items():
            if stage_name in line:
                current_stage = param
                break
        if current_stage:
            if action_install in line:
                line = line.replace(action_install,
                    f"when {{ expression {{ params.ACTION == 'INSTALL' && params.{current_stage} }} }}")
            elif action_uninstall in line:
                line = line.replace(action_uninstall,
                    f"when {{ expression {{ params.ACTION == 'UNINSTALL' && params.{current_stage} }} }}")
        result.append(line)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(result))
    print(f"Updated: {filepath}")
