apiVersion: v1
kind: Service
metadata:
  name: reports-portal-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: reports-portal-service
    domain: platform
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8300
      protocol: TCP
      name: http
  selector:
    app: reports-portal-service
