apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bytebase.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bytebase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bytebase.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bytebase.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: bytebase
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          args:
            - --data
            - {{ .Values.persistence.mountPath }}
            - --external-url
            - {{ .Values.externalUrl }}
            - --port
            - {{ .Values.service.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PG_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bytebase.fullname" . }}-secret
                  key: pg-url
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: bytebase-data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: bytebase-data
          persistentVolumeClaim:
            claimName: {{ include "bytebase.fullname" . }}-pvc
        {{- end }}
