apiVersion: v1
kind: ServiceAccount
metadata:
  name: survey-service
  namespace: customer-experience
  labels:
    app: survey-service
    domain: customer-experience
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-survey-service
