apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracking-service
  namespace: supply-chain
  labels:
    app: tracking-service
    domain: supply-chain
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-tracking-service
