apiVersion: v1
kind: Secret
metadata:
  name: {{ include "driftctl.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "driftctl.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: "changeme-replace-with-real-key"
  aws-secret-access-key: "changeme-replace-with-real-secret"
