plugin: google.cloud.gcp_compute
projects:
  - "{{ lookup('env', 'GCP_PROJECT_ID') }}"
filters:
  - status = RUNNING
  - labels.project = shopos
keyed_groups:
  - key: labels.role
    prefix: role
  - key: labels.environment
    prefix: env
  - key: zone
    prefix: zone
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  ansible_user: "'ubuntu'"
