replicaCount: 1

image:
  repository: loicsharma/baget
  tag: "0.4.0-pre2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
