apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pomerium.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pomerium.labels" . | nindent 4 }}
type: Opaque
stringData:
  shared-secret: {{ .Values.config.sharedSecret | quote }}
  cookie-secret: {{ .Values.config.cookieSecret | quote }}
  idp-client-secret: {{ .Values.config.idpClientSecret | quote }}
