replicaCount: 1

image:
  repository: gcr.io/projectsigstore/fulcio
  tag: "v1.4.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5555
  targetPort: 5555

persistence:
  enabled: true
  storageClass: ""
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
