apiVersion: v1
kind: Service
metadata:
  name: api-key-service
  namespace: identity
  labels:
    app: api-key-service
    domain: identity
spec:
  selector:
    app: api-key-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50066
      targetPort: grpc
      protocol: TCP
