apiVersion: v1
kind: Service
metadata:
  name: price-list-service
  namespace: catalog
  labels:
    app: price-list-service
    domain: catalog
spec:
  selector:
    app: price-list-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50181
      targetPort: grpc
      protocol: TCP
