apiVersion: v1
kind: ServiceAccount
metadata:
  name: price-list-service
  namespace: catalog
  labels:
    app: price-list-service
    domain: catalog
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-price-list-service
