apiVersion: v1
kind: Service
metadata:
  name: consent-management-service
  namespace: customer-experience
  labels:
    app: consent-management-service
    domain: customer-experience
spec:
  selector:
    app: consent-management-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50127
      targetPort: grpc
      protocol: TCP
