apiVersion: v1
kind: ServiceAccount
metadata:
  name: consent-management-service
  namespace: customer-experience
  labels:
    app: consent-management-service
    domain: customer-experience
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-consent-management-service
