replicaCount: 1

image:
  repository: apachepulsar/pulsar
  tag: "4.0.9"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6650
  targetPort: 6650

persistence:
  enabled: true
  storageClass: """"
  size: 20Gi
  accessMode: ReadWriteOnce
  mountPath: /pulsar/data

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi

env:
  PULSAR_MEM: "-Xms1g -Xmx2g -XX:MaxDirectMemorySize=1g"

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
