apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service
  namespace: analytics-ai
  labels:
    app: recommendation-service
    domain: analytics-ai
data:
  APP_ENV: production
  LOG_LEVEL: info
  LOG_FORMAT: json
  SERVICE_NAME: recommendation-service
  SERVICE_DOMAIN: analytics-ai
  GRPC_PORT: "50150"
  METRICS_PORT: "9090"
  HEALTH_PORT: "50150"
  OTEL_SERVICE_NAME: recommendation-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring:4317
  KAFKA_BROKERS: kafka.infra:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.infra:8081
