replicaCount: 1

image:
  repository: quay.io/thanos/thanos
  tag: "v0.36.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 10902
  targetPort: 10902

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 20Gi
  accessMode: ReadWriteOnce
  mountPath: /thanos

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
