apiVersion: v1
kind: ConfigMap
metadata:
  name: edi-service
  namespace: b2b
  labels:
    app: edi-service
    domain: b2b
data:
  APP_ENV: production
  LOG_LEVEL: info
  LOG_FORMAT: json
  SERVICE_NAME: edi-service
  SERVICE_DOMAIN: b2b
  GRPC_PORT: "50165"
  METRICS_PORT: "9090"
  HEALTH_PORT: "50165"
  OTEL_SERVICE_NAME: edi-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring:4317
  KAFKA_BROKERS: kafka.infra:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.infra:8081
