apiVersion: v1
kind: Service
metadata:
  name: worker-job-queue
  namespace: platform
  labels:
    app: worker-job-queue
    domain: platform
spec:
  selector:
    app: worker-job-queue
  type: ClusterIP
  ports:
    - name: grpc
      port: 50057
      targetPort: grpc
      protocol: TCP
