apiVersion: v1
kind: Service
metadata:
  name: currency-service
  namespace: commerce
  labels:
    app: currency-service
    domain: commerce
spec:
  selector:
    app: currency-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50085
      targetPort: grpc
      protocol: TCP
