replicaCount: 1

image:
  repository: docker.io/flannel/flannel
  tag: "v0.25.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 10254
  targetPort: 10254

persistence:
  enabled: false
  storageClass: ""
  size: 1Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
