replicaCount: 2

image:
  repository: harbor.registry.svc.cluster.local/shopos/reports-portal-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8300

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: reports.shopos.internal
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  PORT: "8300"
  GRAFANA_URL: "http://grafana-grafana.grafana.svc.cluster.local:3000"
  PROMETHEUS_URL: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
  ALERTMANAGER_URL: "http://prometheus-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093"
  JAEGER_URL: "http://jaeger-query.observability.svc.cluster.local:16686"
  ZIPKIN_URL: "http://zipkin.observability.svc.cluster.local:9411"
  TEMPO_URL: "http://tempo.observability.svc.cluster.local:3200"
  KIBANA_URL: "http://kibana.observability.svc.cluster.local:5601"
  OPENSEARCH_DASHBOARDS_URL: "http://opensearch-dashboards.observability.svc.cluster.local:5601"
  PYROSCOPE_URL: "http://pyroscope.observability.svc.cluster.local:4040"
  SIGNOZ_URL: "http://signoz-frontend.observability.svc.cluster.local:3301"
  GLITCHTIP_URL: "http://glitchtip.observability.svc.cluster.local:8000"
  UPTIME_KUMA_URL: "http://uptime-kuma.observability.svc.cluster.local:3001"
  JENKINS_URL: "http://jenkins.ci.svc.cluster.local:8080"
  ARGOCD_URL: "http://argocd-server.argocd.svc.cluster.local:80"
  ARGO_WORKFLOWS_URL: "http://argo-workflows-server.argo.svc.cluster.local:2746"
  FLUX_URL: "http://weave-gitops.flux-system.svc.cluster.local:9001"
  HARBOR_URL: "http://harbor.registry.svc.cluster.local:80"
  NEXUS_URL: "http://nexus-nexus-repository-manager.registry.svc.cluster.local:8081"
  GITEA_URL: "http://gitea.registry.svc.cluster.local:3000"
  SONARQUBE_URL: "http://sonarqube.security.svc.cluster.local:9000"
  DEFECTDOJO_URL: "http://defectdojo.security.svc.cluster.local:8080"
  DEPENDENCY_TRACK_URL: "http://dependency-track.security.svc.cluster.local:8080"
  VAULT_URL: "http://vault.security.svc.cluster.local:8200"
  KEYCLOAK_URL: "http://keycloak.security.svc.cluster.local:8080"
  WAZUH_URL: "http://wazuh-dashboard.security.svc.cluster.local:5601"
  REKOR_URL: "http://rekor-server.security.svc.cluster.local:3000"
  PACT_BROKER_URL: "http://pact-broker.platform.svc.cluster.local:9292"
  AKHQ_URL: "http://akhq.messaging.svc.cluster.local:8080"
  KAFKA_UI_URL: "http://kafka-ui.messaging.svc.cluster.local:8080"
  RABBITMQ_URL: "http://rabbitmq.messaging.svc.cluster.local:15672"
  NATS_MON_URL: "http://nats.messaging.svc.cluster.local:8222"
  CONDUKTOR_URL: "http://conduktor-platform.messaging.svc.cluster.local:8080"
  AIRFLOW_URL: "http://airflow-webserver.data.svc.cluster.local:8080"
  PREFECT_URL: "http://prefect-server.data.svc.cluster.local:4200"
  DAGSTER_URL: "http://dagster-dagit.data.svc.cluster.local:3000"
  MARQUEZ_URL: "http://marquez-web.data.svc.cluster.local:3000"
  SUPERSET_URL: "http://superset.data.svc.cluster.local:8088"
  MLFLOW_URL: "http://mlflow.ml.svc.cluster.local:5000"
  BACKSTAGE_URL: "http://backstage.platform.svc.cluster.local:7007"
  TEMPORAL_URL: "http://temporal-web.platform.svc.cluster.local:8080"
  UNLEASH_URL: "http://unleash.platform.svc.cluster.local:4242"
  CHAOS_MESH_URL: "http://chaos-dashboard.chaos-mesh.svc.cluster.local:2333"
  LITMUS_URL: "http://litmusportal-frontend.litmus.svc.cluster.local:9091"

livenessProbe:
  httpGet:
    path: /healthz
    port: 8300
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 8300
  initialDelaySeconds: 3
  periodSeconds: 5
