apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boundary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "boundary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boundary.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: boundary
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          args:
            - server
            - -config=/boundary/config/boundary.hcl
          ports:
            - name: api
              containerPort: 9200
              protocol: TCP
            - name: cluster
              containerPort: 9201
              protocol: TCP
            - name: data
              containerPort: 9202
              protocol: TCP
          env:
            - name: BOUNDARY_PG_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "boundary.fullname" . }}-secret
                  key: database-url
          livenessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
