apiVersion: v1
kind: Service
metadata:
  name: cache-warming-service
  namespace: platform
  labels:
    app: cache-warming-service
    domain: platform
spec:
  selector:
    app: cache-warming-service
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
