apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  namespace: financial
  labels:
    app: accounting-service
    domain: financial
spec:
  selector:
    app: accounting-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50111
      targetPort: grpc
      protocol: TCP
