apiVersion: v1
kind: ServiceAccount
metadata:
  name: accounting-service
  namespace: financial
  labels:
    app: accounting-service
    domain: financial
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-accounting-service
