apiVersion: v1
kind: ServiceAccount
metadata:
  name: cms-service
  namespace: content
  labels:
    app: cms-service
    domain: content
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-cms-service
