replicaCount: 1

image:
  repository: jaegertracing/all-in-one
  tag: "1.61.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 16686
  targetPort: 16686

persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /var/lib/data

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
