replicaCount: 1

image:
  repository: ghcr.io/authelia/authelia
  tag: "4.38.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9091
  targetPort: 9091

persistence:
  enabled: true
  storageClass: ""
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
