apiVersion: v1
kind: Service
metadata:
  name: data-export-service
  namespace: content
  labels:
    app: data-export-service
    domain: content
spec:
  selector:
    app: data-export-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50147
      targetPort: grpc
      protocol: TCP
