replicaCount: 1

image:
  repository: docker.redpanda.com/redpandadata/redpanda
  tag: "v24.2.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9092
  targetPort: 9092

persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /var/lib/data

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
