replicaCount: 1

image:
  repository: prom/prometheus
  tag: "v2.54.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090
  targetPort: 9090

persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce
  mountPath: /var/lib/data

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
