apiVersion: v1
kind: Service
metadata:
  name: seo-service
  namespace: catalog
  labels:
    app: seo-service
    domain: catalog
spec:
  selector:
    app: seo-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50079
      targetPort: grpc
      protocol: TCP
