apiVersion: v1
kind: ServiceAccount
metadata:
  name: mobile-bff
  namespace: platform
  labels:
    app: mobile-bff
    domain: platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-mobile-bff
