apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlantis.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-user: {{ .Values.vcs.githubUser | quote }}
  github-token: {{ .Values.vcs.githubToken | quote }}
  webhook-secret: {{ .Values.vcs.webhookSecret | quote }}
