apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: catalog
  labels:
    app: inventory-service
    domain: catalog
spec:
  selector:
    app: inventory-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50074
      targetPort: grpc
      protocol: TCP
