apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-pipeline-service
  namespace: analytics-ai
  labels:
    app: data-pipeline-service
    domain: analytics-ai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-data-pipeline-service
