apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  namespace: analytics-ai
  labels:
    app: sentiment-analysis-service
    domain: analytics-ai
spec:
  selector:
    app: sentiment-analysis-service
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
