replicaCount: 1

image:
  repository: falcosecurity/falco-no-driver
  tag: "0.39.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8765
  targetPort: 8765

persistence:
  enabled: true
  storageClass: ""
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
