replicaCount: 1

image:
  repository: prom/alertmanager
  tag: "v0.27.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9093
  targetPort: 9093

persistence:
  enabled: true
  storageClass: "standard-rwo"
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /alertmanager

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
