apiVersion: v1
kind: Service
metadata:
  name: supplier-portal-service
  namespace: supply-chain
  labels:
    app: supplier-portal-service
    domain: supply-chain
spec:
  selector:
    app: supplier-portal-service
  type: ClusterIP
  ports:
    - name: http
      port: 8088
      targetPort: http
      protocol: TCP
