apiVersion: v1
kind: ServiceAccount
metadata:
  name: pim-integration-service
  namespace: integrations
  labels:
    app: pim-integration-service
    domain: integrations
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-pim-integration-service
