apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: supply-chain
  labels:
    app: tracking-service
    domain: supply-chain
spec:
  selector:
    app: tracking-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50104
      targetPort: grpc
      protocol: TCP
