apiVersion: v1
kind: Service
metadata:
  name: recently-viewed-service
  namespace: customer-experience
  labels:
    app: recently-viewed-service
    domain: customer-experience
spec:
  selector:
    app: recently-viewed-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50124
      targetPort: grpc
      protocol: TCP
