apiVersion: v1
kind: ServiceAccount
metadata:
  name: recently-viewed-service
  namespace: customer-experience
  labels:
    app: recently-viewed-service
    domain: customer-experience
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-recently-viewed-service
