replicaCount: 1

image:
  repository: codeberg.org/forgejo/forgejo
  tag: "9.0.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

persistence:
  enabled: true
  storageClass: """"
  size: 20Gi
  accessMode: ReadWriteOnce
  mountPath: /data

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

env: {}

ingress:
  enabled: false
  className: ""
  host: ""
  tls: []
