apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-feature-store
  namespace: analytics-ai
  labels:
    app: ml-feature-store
    domain: analytics-ai
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-feature-store
  template:
    metadata:
      labels:
        app: ml-feature-store
        domain: analytics-ai
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "50152"
    spec:
      serviceAccountName: ml-feature-store
      terminationGracePeriodSeconds: 30
      containers:
        - name: ml-feature-store
          image: shopos/ml-feature-store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50152
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ml-feature-store
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 2Gi
          livenessProbe:
            tcpSocket:
              port: 50152
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 50152
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: ml-feature-store
