apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-bff
  namespace: platform
  labels:
    app: web-bff
    domain: platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-web-bff
