apiVersion: v1
kind: ServiceAccount
metadata:
  name: saga-orchestrator
  namespace: platform
  labels:
    app: saga-orchestrator
    domain: platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/shopos-saga-orchestrator
