apiVersion: v1
kind: ConfigMap
metadata:
  name: permission-service
  namespace: identity
  labels:
    app: permission-service
    domain: identity
data:
  APP_ENV: production
  LOG_LEVEL: info
  LOG_FORMAT: json
  SERVICE_NAME: permission-service
  SERVICE_DOMAIN: identity
  GRPC_PORT: "50063"
  METRICS_PORT: "9090"
  HEALTH_PORT: "50063"
  OTEL_SERVICE_NAME: permission-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring:4317
  KAFKA_BROKERS: kafka.infra:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.infra:8081
