apiVersion: v1
kind: Service
metadata:
  name: permission-service
  namespace: identity
  labels:
    app: permission-service
    domain: identity
spec:
  selector:
    app: permission-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50063
      targetPort: grpc
      protocol: TCP
