apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: catalog
  labels:
    app: product-catalog-service
    domain: catalog
spec:
  selector:
    app: product-catalog-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 50070
      targetPort: grpc
      protocol: TCP
