apiVersion: v1
kind: Service
metadata:
  name: whatsapp-service
  namespace: communications
  labels:
    app: whatsapp-service
    domain: communications
spec:
  selector:
    app: whatsapp-service
  type: ClusterIP
  ports:
    - name: http
      port: 3020
      targetPort: http
      protocol: TCP
